
  # Jwt 토큰에 들어가는 secret 값
spring:


  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  # database 연결관련, 개발환경 (mysql)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel5.cloudtype.app:30691/test?createDatabaseIfNotExist=true
    username: root
    password: qwer1234

  # 배포환경은 (maria DB)

